# Generated by Django 5.1.2 on 2024-11-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_alter_category_options_post_post_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
