# Generated by Django 5.1.2 on 2024-11-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
