# Generated by Django 5.1.2 on 2024-11-05 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0004_alter_book_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
